### ISSUE TITLE
How to get the spaceID

### ISSUE THREAD

**Issue by agorostidi** [van-ibm/watsonworkspace-starter#1]
@dcacy   On the code sample, and on the video of van,  there is a

const spaceId = "PUTYOURSPACEIDHERE"

Is there any way to get the spaceID automatically, using code, instead hardcoding it ?

**Comment by dcacy** [comment]
@agorostidi, the spaceId is part of the message object which is passed to the event handler (the `bot.on` code).  From the sample code in this project, you can see it in action:

![image](https://user-images.githubusercontent.com/15927428/40684036-da663c26-6355-11e8-93ba-10fb533dd25a.png)

If you want to get all the spaces to which your app has been added, you can do that with a graphQl command:

`query getSpaces { spaces(first: 20) {items {title id}}}`

Does this help?

**Comment by agorostidi** [comment]
Yes, it helps MOST of the cases, thks, however there is still a specific case where is not enough, because I need to do a post on the message before I get any bot.on event....

As here:

const spaceId = '5b0a66dee4b0e097f5397dca'

/*
// send a simple message as a bot
bot.authenticate()
 .then(token => {
   //Some process here, to do some initial configuration and calls to external apps
  bot.sendMessage(message, ' Thks for using MyApp.  We are ready to go !')
})
*/

**Comment by dcacy** [comment]
It's important to remember that an app can only post a message to a space to which it has been added.  You can get a list of all the spaces the app has been added to with the graphQl query I posted above.  Then you can decide which space will receive your message.

If you want to do some initialization when the app is added to a space, I don't recommend doing so on the `bot.authenticate`, since that code will run only one time -- when the app starts up.  If you add the app to a space later, that code won't run a second time.

Instead, I suggest you use the `space-members-added` event, which will be invoked when the app is added to a space (or when members are added).  Here's some code from one of my apps:

```
bot.on('space-members-added', (message) => {
  handleSetup.initialize(message);
});
```
In my `handleSetup.initialize` code, I figure out if the app has been configured or if it was just added, and then I can welcome the user or whatever. This has the advantage of receiving the `message` object, which contains the `spaceId`.

If you need to send a message to all spaces, you can do something like this pseudocode:

```
bot.sendGraphql('query getSpaces { spaces {items {id}}}')
.then(result => {
   for(var i = 0; i < result.length; i++) {
      postMessage(result[i].id);
   }
}
```

**Comment by agorosti** [comment]
Thks, that is exactly what I need !
